version: '3.2'

services:
  db:
    image: mysql:8.0.32
    container_name: database-alimentacao
    restart: always
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: alimentacao-db
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    # Names our volume
volumes:
  my-db: